

export const TASK_PRIORITY_HIGH = 0;
export const TASK_PRIORITY_MEDIUM = 1;
export const TASK_PRIORITY_LOW = 2;

export const USER_ROLE_HOTSEAT = "USER_ROLE_HOTSEAT"
export const USER_ROLE_REPORTER = "USER_ROLE_REPORTER"
export const USER_ROLE_NEWSASSOCIATE = "USER_ROLE_NEWSASSOCIATE"
export const USER_ROLE_COPYEDITOR = "USER_ROLE_COPYEDITOR"
export const USER_ROLE_EDITOR = "USER_ROLE_EDITOR"
export const USER_ROLE_VIDEOPRODUCER = "USER_ROLE_VIDEOPRODUCER"
export const USER_ROLE_PHOTODESK = "USER_ROLE_PHOTODESK"
export const USER_ROLE_SITEPRODUCER = "USER_ROLE_SITEPRODUCER"
export const USER_ROLE_SOCIAL = "USER_ROLE_SOCIAL"

export const SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/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"

